apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-perfect-little-website
spec:
  selector:
    matchLabels:
      app: my-perfect-little-website
  template:
    metadata:
      labels:
        app: my-perfect-little-website
    spec:
      containers:
      - name: my-perfect-little-website
        image: ofekinger/my-perfect-little-website:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
